# Generated by Django 3.2.8 on 2021-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betask',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
